### ISSUE TITLE
Crash when called on Template.language

### ISSUE THREAD

**Issue by Heimdell** [pietervdvn/ALGT2#1]
In its current state it looks unusable for me.

1) Building: `stack install` works, why bother with `./build.sh` (which doesn't w/o (write?) access to repository)?

2) Building: doesn't generate `ALGT` executable. Generates `ALGT2-exe` instead. Are they the same thing?

3) Security: repository contains executables. Will they steal my passwords?

2) Usage: You have to call `ALGT` from `./ALGT2/src` and conduct other manipulations. And then it crashes.
```
ALGT2/src $ ALGT2-exe --template
ALGT2/src $ ALGT2-exe . Template.language
Reloading ./Template/language
ALGT: src/Utils/PureIO.hs:(52,1)-(71,19): Non-exhaustive patterns in function runIO'
```

I appreciate the idea, because sometimes I look for frameworks like this.

**Comment by pietervdvn** [comment]
1) Because of some preprocessing which should be done in a cleaner way... I set it up so that `stack build` should work

2) ALGT is the same as ALGT2-exe, it is copied for convenience

3) Executables are for those who are to lazy to build from stack themselves. I moved them somewhat more out of sight. And no, it won't steal your passwords (at most your bitcoins :p )

4) That bug should have been fixed by now
